### ISSUE TITLE
Jp2 file with numTiles >1,1

### ISSUE THREAD

**Issue by mgholam** [cureos/csj2k#13]
I have a jp2 file which opens correctly in FastStone Image viewer (a scanned document) which renders garbled with the library.

On debugging I have found that numTiles [j2kimage.cs line 221] for this file is not 1,1 dimension and is in fact 2,4 

How can this be fixed?

Thanks Mehdi

**Comment by anders9ustafsson** [comment]
@mgholam Thanks for reporting. Are you able to provide the file here so that we can test it?

**Comment by mgholam** [comment]
Yes Anders, can you send me your email.

**Comment by anders9ustafsson** [comment]
@mgholam The simplest thing is probably if you upload the image to this issue. If the file extension is not supported for upload, you may zip the file before you upload it. Making it public has the benefit that others in the community can examine it as well.

If you prefer to send it to me personally, you can reach me at "info at cureos dot com". I cannot promise that I have time to look at the image soon though, but I'll let you know when I have examined it in greater detail.

**Comment by mgholam** [comment]
Thanks

**Comment by mgholam** [comment]
Found the bug!
change `j2kimage.cs` `FromSteam()` to :
```
    dst.FillRow(tOffx, tOffy + l, decodedImage.ImgWidth, rowvalues);
```
and the `FillRow()` in `portableimage.cs` to :
```
        internal void FillRow(int x, int y, int rowWidth, byte[] rowValues)
        {
            switch (this.NumberOfComponents)
            {
                case 1:
                case 3:
                    var i = SizeOfArgb * (x + y * rowWidth);
                    var j = 0;
                    for (var k = 0; k < rowValues.Length / this.NumberOfComponents; k++)
                    {
                        this.Bytes[i++] = rowValues[j++];
                        this.Bytes[i++] = rowValues[j++];
                        this.Bytes[i++] = rowValues[j++];
                        this.Bytes[i++] = 0xff;
                    }
                    //Array.Copy(
                    //    rowValues,
                    //    0,
                    //    this.Bytes,
                    //    SizeOfArgb * (x + y * rowWidth),
                    //    rowValues.Length);
                    break;
                case 4:
                    Array.Copy(
                        rowValues,
                        0,
                        this.Bytes,
                        SizeOfArgb * (x + y * rowWidth),
                        SizeOfArgb * rowWidth);
                    break;
                default:
                    throw new InvalidOperationException("Number of components must be one of 1, 3 or 4.");
            }
        }
```

**Comment by mgholam** [comment]
Also can we change `SizeOfArgb = 3` to save space? 
I have done that but the image is skewed, what have I missed?

**Comment by anders9ustafsson** [comment]
@mgholam Wonderful! Many many thanks for digging deeper into this problem! I will update the code with your fix as soon as possible.

`SizeOfArgb` is 4 by necessity, one byte per component alpha, red, green, blue. I am not sure how much work it would be to optimize the memory consumption for RGB; there is an apparent risk that much of the implementation relies on 4 bytes per pixel implicitly.
