### ISSUE TITLE
If newer WriteableBitmapEx is used, exception occurs

### ISSUE THREAD

**Issue by programatix** [cureos/csj2k#2]
Hi,

I upgraded WriteableBitmapEx to version 1.5.0 (via NuGet) and whenever I call CSJ2K.J2kImage.FromBytes(), exception occurs stating that WriteableBitmapEx  1.0.6 is not found.

Thanks.

**Comment by anders9ustafsson** [comment]
Interesting! Looking at [packages.config](https://github.com/cureos/csj2k/blob/master/WPF.CSJ2K/packages.config) for the WPF instance the target framework has been set to .NET 4.5, and there are similar issues in the corresponding files for the _SL.CSJ2K_ and _WP.CSJ2K_ projects.

Please try and remove the `targetFramework` specification from the _packages.config_ files to see if _WriteableBitmapEx_ will be correctly found then.

**Comment by programatix** [comment]
The problem seems to be resolved. What I did was to totally remove csj2k and WriteableBitmapEx from my solution. Close it and clean up the NuGet packages folder. Re-open and add csj2k, followed by updating WriteableBitmapEx. It know execute without causing exception.

Thanks for looking into the problem I've reported.

Date: Wed, 22 Apr 2015 05:55:51 -0700
