### ISSUE TITLE
License problems

### ISSUE THREAD

**Issue by bsivanov** [cureos/csj2k#3]
I am not sure this would be useful, but our legal team just reviewed the license of the product, as we were planning to use it in commercial product. 

The conclusion was that the license is strange and that products using the code must conform to the [ISO/IEC 15444-1](http://www.iso.org/iso/catalogue_detail.htm?csnumber=37674) standard - something that is very time-consuming to verify. Too bad that such good project is restricted by a bad license - I guess applied by its original authors 15 years ago.

**Comment by anders9ustafsson** [comment]
Thanks for pointing out this problem, I totally agree with your concern. I'll investigate if there is anything that can be done about this issue, and get back as soon as possible.

Best regards,
Anders

**Comment by anders9ustafsson** [comment]
Have made further investigations, but unfortunately there is little I can do about the original JJ2000 license, since it also includes derivative works. License stands.
