### ISSUE TITLE
Encoder quality setting

### ISSUE THREAD

**Issue by SylvainDebaudringhien** [cureos/csj2k#4]
Hi.
JJ2000 supports quality settings (bit per pixel at least, and maybe more, like target file size) in the encoder.

Do you think it would be possible to add quality/target size settings to CSJ2K.ToBytes(...)?

Thanks,
Sylvain.

**Comment by anders9ustafsson** [comment]
@sylvain46 Very good that you highlighted this. I have planned to implement support for various configuration parameters, but I have not yet had the time to do it. When time permits, I will deal with this issue.

Best regards,
Anders
