### ISSUE TITLE
No CSJ2K.dll for WinForms apps in NuGet package

### ISSUE THREAD

**Issue by vladimir-poleh** [cureos/csj2k#6]
Hi, package available via NuGet  does not contain library for WinForms.
I still able to build WinForms dll from sources, but it is less usefull than NuGet package.

Could you please update package to have libraries for all platforms?

**Comment by anders9ustafsson** [comment]
Many thanks for your suggestion, @vladimir-poleh , good idea!

I will deal with this when time permits. In the meantime, it is good that you have applied a workaround.

Best regards,
Anders @ Cureos
