### ISSUE TITLE
How to encode a uncompressed bytearray to a Jpeg2000 bytearray

### ISSUE THREAD

**Issue by AndreasSchmid1** [cureos/csj2k#7]
As described in the documentation, encoding of Bitmap/WriteableBitmap is currently not supported.
Can you please provide a sample how to convert a Bitmap/WriteableBitmap to a CSJ2K supported format?

Thank you for help in advance

**Comment by anders9ustafsson** [comment]
@AndreasSchmid1 You will need to convert your bitmap file to a _Portable Bitmap_ (PBM) before you can call the encoder method. 

I have not been able to find any Windows based open-source project that provides this functionality, but the NetPBM Linux project provides a converter. If you want to try a few samples out, you should also be able to find some free online converters.

**Comment by anders9ustafsson** [comment]
Just to add: [here](http://rosettacode.org/wiki/Bitmap/Write_a_PPM_file#C.23) is a C# version of simple code to write a _Portable Bitmap_ file from known bitmap data. It should be an easy task to load a `System.Drawing.Bitmap` or a `WriteableBitmap` and transfer the individual pixels of that bitmap to PBM with the help of the linked code.

**Comment by AndreasSchmid1** [comment]
Thank you very much! I will check it out
