### ISSUE TITLE
Does not work with WriteableBitmapEx.Wpf ver 1.5.0.0

### ISSUE THREAD

**Issue by AlexeiScherbakov** [cureos/csj2k#9]
Does not work with WriteableBitmapEx.Wpf 1.5.0.0 - it tries to load 1.0.6.0 version

**Comment by anders9ustafsson** [comment]
Thanks for reporting. Will look into this as soon as possible.

**Comment by anders9ustafsson** [comment]
@AlexeiScherbakov Have you tried to update _WriteableBitmapEx_ after downloading _CSJH2K_ from NuGet? I am about to update _CSJ2K_ to a more modern PCL profile right now, and I have no problems upgrading _WriteableBitmapEx_ to 1.5.0 at the same time.

**Comment by anders9ustafsson** [comment]
@AlexeiScherbakov In the upcoming release, _WriteableBitmapEx_ is no longer required.
